openapi: 3.0.0
info:
  title: Auth Service API
  description: API documentation for the Authentication microservice.
  version: 1.0.0
servers:
  - url: http://api.example.com/auth
    description: Production server
paths:
  /login:
    post:
      summary: User login
      description: Authenticate user credentials and generate access token.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: User's username or email
                password:
                  type: string
                  description: User's password
              required:
                - username
                - password
      responses:
        '200':
          description: User authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  accessToken:
                    type: string
                    description: JWT access token
        '401':
          description: Invalid credentials
components:
  schemas:
    UserCredentials:
      type: object
      properties:
        username:
          type: string
          description: User's username or email
        password:
          type: string
          description: User's password
      required:
        - username
        - password
