version: '3.8'

services:
#  backend:
#    image: reminder-backend:v1
#    ports:
#      - "8080:8080"
#    networks:
#      - backend-network
#    depends_on:
#      - mongodb
#      - localstack

#  frontend:
#    image: reminder-frontend:v1
#    ports:
#      - "80:80"
#    networks:
#      - frontend-network

  mongodb:
    image: mongo:latest
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: reminder_db
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network
    ports:
      - "27017:27017"

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"  
    environment:
      - SERVICES=s3,sqs,sns
      - DEFAULT_REGION=us-east-1
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
