@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Container(backend, "Backend", "Java Spring Boot", "Application backend")
System_Boundary(Infrastructure, "AWS Infrastructure") {
    Container(EC2, "EC2 Instance", "AWS EC2", "Cloud Virtual Machine")
    Container(S3, "S3", "AWS S3", "Static File Storage")
    ContainerDb(DocumentDB, "DocumentDB", "AWS DocumentDB", "NoSQL Database")

    Rel(backend, DocumentDB, "Accesses data", "MongoDB")
}

@enduml